name: hishabee_business_manager_fl
description: HishaBee Business Manager App in flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
#  month_picker_dialog: ^0.4.0
  url_launcher: ^6.0.12
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5

  get: ^4.3.8
  flutter_staggered_grid_view: ^0.4.1
  fluttertoast: ^8.0.8
#  sslcommerz_flutter: ^0.0.4
  carousel_pro: ^1.0.0
  showcaseview: ^1.1.1
  youtube_player_flutter: ^8.0.0
  #  data_connection_checker: ^0.3.4
  #charts_flutter: ^0.11.0
  pinput: ^1.2.1
#  google_maps_place_picker: ^1.0.1
  google_maps_flutter: ^2.0.11
  animated_widgets: ^1.1.0
  cached_network_image: ^3.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  connectivity_plus: ^2.0.2
  flutter_keyboard_aware_dialog: ^1.0.1
  flutter_share: ^2.0.0
  clipboard: ^0.1.3
  group_button: ^3.3.1
#  workmanager: ^0.2.3
  confetti: ^0.6.0
  flutter_switch: ^0.3.2
  flutter_grid_button: ^2.0.0
  rect_getter: ^1.0.0
  math_expressions: ^2.2.0
  flutter_svg: ^0.23.0+1
  flutter_spinkit: ^5.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  input_calculator: ^2.0.0
  cupertino_icons: ^1.0.3
  uuid: ^3.0.5
  freezed_annotation: ^0.15.0
  json_annotation: ^4.1.0
  darq: ^1.1.1
  date_util: ^0.1.4
  webview_flutter: ^2.1.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_messaging: ^10.0.8
  firebase_analytics: ^8.3.3
  facebook_app_events: ^0.13.5
  share_plus: ^3.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^9.0.0
  pdf: ^3.6.0
  printing: ^5.6.0
  flutter_open_whatsapp: ^0.1.2
  number_display: ^3.0.0
  qr_flutter: ^4.0.0
  app_tracking_transparency: ^2.0.2+1
  flutter_native_splash: ^1.2.4
  in_app_purchase: ^1.0.9
  #shared_preferences: ^0.5.12+4
  http: ^0.13.4
  flutter_simple_calculator: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  get_storage: ^2.0.3
  loading_overlay: ^0.3.0


dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^5.0.2
  build_runner: any
#flutter_native_splash:
  #fullscreen: true
  #color: "#ffffff"
  #image: images/splash.png
  #android: false
  #ios: true
  #android_gravity: fill
  #ios_content_mode: scalAspectFill


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/shop_features/
    - images/icons/
    - images/xml_icon/
    - images/svg_image/
    - images/slider/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Hind_Siliguri
      fonts:
        - asset: fonts/Hind_Siliguri-Regular_GhOgZt6.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf
        - asset: fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic
#        - asset: fonts/Hind_Siliguri-Regular_GhOgZt6.ttf
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages